KEY_BOARD_INT_NUM = 16
SCREEN_MMAP_ADDR = 0xb8000
KEY_MMAP_ADDR = 0xb8d70

REG_SCREEN_START_Y = 1
REG_SCREEN_START_X = 0
REG_SCREEN_HEIGHT = 23
REG_SCREEN_WIDTH = 31

STACK_SCREEN_START_Y = REG_SCREEN_START_Y
STACK_SCREEN_START_X = REG_SCREEN_WIDTH + 2
STACK_SCREEN_HEIGHT = 10
STACK_SCREEN_WIDTH = 24


SCREEN_START_Y = 12
SCREEN_START_X = 33
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 25
SCREEN_REFRESH_FREQ = 24

DEFAULT_MEMORY_SIZE = 64